spring.application.name=gestione-ordini
# Indirizzo del database (localhost perché Docker è sul tuo PC)
spring.datasource.url=jdbc:mysql://localhost:3306/gestione_ordini
spring.datasource.username=root
spring.datasource.password=
# Hibernate crea le tabelle per te partendo dalle classi Java (@Entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true